FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y     docker.io     make     g++     curl

# Create docker group with same GID as host (replace 998 with yours)
RUN groupadd -g 1001 docker || true

# Add jenkins user to docker group
RUN usermod -aG docker jenkins

USER jenkins
